spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect:
          nodeValue:
            org.hibernate.dialect.MySQL57Dialect
          storage_engine: innodb


